### ISSUE TITLE
Mashing space while starting a playtest in the editor crashes the game

### ISSUE THREAD

**Issue by 128x16** [geode-sdk/CustomKeybinds#53] opened 2024-06-20 15:21 UTC
I can reproduce this by simply spamming the playtest button and space at the same time
Doesn't seem to happen with the up arrow
[2024-06-20_16-17-09.log](https://github.com/user-attachments/files/15916232/2024-06-20_16-17-09.log)

**Comment by cameronaw13** [comment] 2024-06-23 20:18
Was able to reproduce this, here's my crashlog as well
[2024-06-23_21-16-50.txt](https://github.com/user-attachments/files/15945870/2024-06-23_21-16-50.txt)

**Comment by Cvolton** [comment] 2024-07-03 22:44
does this still happen on the latest versions of geode and custom keybinds?

**Comment by Cvolton** [comment] 2024-07-03 22:45
caused by an upstream bug in geode, should be fixed by now, please reopen with an updated crash log if it still happens on the latest versions of geode and custom keybinds

**Closed by Cvolton** 2024-07-03 22:45 UTC
