### ISSUE TITLE
constant crashes

### ISSUE THREAD

**Issue by 00vvlc** [geode-sdk/CustomKeybinds#46] opened 2024-05-07 04:50 UTC
I don't know why it is but my game became very unstable, I leave you the crashlog.

2024-05-07T00:49:57-0400
I just don't know what went wrong :(

== Geode Information ==
- Working Directory: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash
- Loader Version: v2.0.0-beta.25 (Geometry Dash v2.204)
- Loader Commit: 20dc3c9
- Bindings Commit: 2eb85b0
- Installed Mods: 66 (Loaded: 64/64)
- 4GB Patch: Patched
- Problems: 0

== Exception Information ==
- Thread Information: "Main" (ID: 2540)
- Exception Code: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
- Exception Address: geode.custom-keybinds.dll+0x4EE46 (keybinds::DeviceFilter::`default constructor closure'+0x19c96)
- Exception Flags: 0x0
- Exception Parameters: 0x0, 0x0
- Access Violation Type: Read
- Access Violation Address: 0x00000000
- Protect: PAGE_NOACCESS (0x1)
- State: MEM_FREE (0x10000)
- Type: Unknown (0x0)

== Stack Trace ==
- geode.custom-keybinds.dll+0x4EE46 (keybinds::DeviceFilter::`default constructor closure'+0x19c96)
- geode.custom-keybinds.dll+0x28C93 (geode::EventFilter<keybinds::InvokeBindEvent>::getListener+0x60d3)
- Geode.dll+0x5E8C3 (geode::DefaultEventListenerPool::handle+0x43)
└ D:\a\geode\geode\loader\src\loader\Event.cpp:33
- Geode.dll+0x5ED1C (geode::Event::postFromMod+0x1c)
└ D:\a\geode\geode\loader\src\loader\Event.cpp:91
- geode.custom-keybinds.dll+0x2D657 (keybinds::BindManager::onDispatch+0x477)
- geode.custom-keybinds.dll+0x2C549 (keybinds::PressBindFilter::handle+0x49)
- geode.custom-keybinds.dll+0x222B3 (geode::EventFilter<keybinds::DeviceEvent>::getPool+0xb3)
- Geode.dll+0x5E8C3 (geode::DefaultEventListenerPool::handle+0x43)
└ D:\a\geode\geode\loader\src\loader\Event.cpp:33
- Geode.dll+0x5ED1C (geode::Event::postFromMod+0x1c)
└ D:\a\geode\geode\loader\src\loader\Event.cpp:91
- geode.custom-keybinds.dll+0x51DC5 (keybinds::DeviceFilter::`default constructor closure'+0x1cc15)
- geode.custom-keybinds.dll+0x5161D (keybinds::DeviceFilter::`default constructor closure'+0x1c46d)
- thesillydoggo.entersearch.dll+0x44FD
- zilko.better_screenshots.dll+0x20454 (<0x20440>+0x14)
- 0x02AC12AF
- libcocos2d.dll+0xC7841 (cocos2d::CCEGLView::onGLFWKeyCallback+0x1e1)
- libcocos2d.dll+0x116C7E (cocos2d::CCPoint::unrotate+0x1f3e)
- libcocos2d.dll+0x1185D6 (cocos2d::CCPoint::unrotate+0x3896)
- absolllute.megahack.dll+0x1454FC (<0x145030>+0x4cc)
- USER32.dll+0x4194B (AddClipboardFormatListener+0x4b)
- USER32.dll+0x37D6A (GetClassLongW+0x7aa)
- USER32.dll+0x37526 (GetSystemMetricsForDpi+0xc46)
- USER32.dll+0x35D4B (CallWindowProcW+0x1b)
- OPENGL32.dll+0x4680F (glDebugEntry+0xe2f)
- USER32.dll+0x4194B (AddClipboardFormatListener+0x4b)
- USER32.dll+0x37D6A (GetClassLongW+0x7aa)
- USER32.dll+0x366A1 (DispatchMessageW+0x4f1)
- USER32.dll+0x361C0 (DispatchMessageW+0x10)
- gameoverlayrenderer.dll+0x840C1 (OverlayHookD3D3+0x1dfb1)
- libcocos2d.dll+0x117472 (cocos2d::CCPoint::unrotate+0x2732)
- 0x02AC2F69
- 0x02AC2B8B
- GeometryDash.exe+0x3C12D8 (<0x3c10f0>+0x1e8)
- Geode.dll+0x1759D4 (gdMainHook+0x214)
└ D:\a\geode\geode\loader\src\platform\windows\main.cpp:59
- GeometryDash.exe+0x3C267E (<0x3c1710>+0xf6e)
- KERNEL32.DLL+0x1FCC9 (BaseThreadInitThunk+0x19)
- ntdll.dll+0x67CBE (RtlGetAppContainerNamedObjectPath+0x11e)
- ntdll.dll+0x67C8E (RtlGetAppContainerNamedObjectPath+0xee)

== Register States ==
- EAX: 00000000 (0i | 0u)
- EBX: 00000001 (1i | 1u)
- ECX: 20C8B908 (-> 0x6F67EC -> 0x651742 -> GeometryDash.exe+0x3C1742 (<0x3c1710>+0x32))
- EDX: 006F67EC (-> 0x651742 -> GeometryDash.exe+0x3C1742 (<0x3c1710>+0x32))
- ESI: 00000000 (0i | 0u)
- EDI: 1F0A47D8 (-> 0x72D050 -> 0x651742 -> GeometryDash.exe+0x3C1742 (<0x3c1710>+0x32))
- EBP: 00EFED24 (-> 0xEFED4C -> 0xEFED8C -> 0x55C9E684 -> 0x55C9C751 -> geode.custom-keybinds.dll+0x1EC751 (keybinds::DeviceFilter::`default constructor closure'+0x1b75a1))
- ESP: 00EFECA4 (-> 0xEFECD3 -> 0x1)
- EIP: 55AFEE46 (geode.custom-keybinds.dll+0x4EE46 (keybinds::DeviceFilter::`default constructor closure'+0x19c96))
- AF: 0 | CF: 0 | DF: 0 
- IF: 1 | OF: 0 | PF: 0 
- SF: 0 | TF: 0 | ZF: 0 

== Installed Mods ==
x | [v1.0.5] abb2k.backup
x | [v8.0.0-alpha.134] absolllute.megahack
x | [v1.0.1] alphalaneous.ezclipboard
x | [v1.1.3] alphalaneous.projectedstars
x | [v1.0.0] alphalaneous_raydeeux.changefont19
x | [v1.1.2] avscs.noshake
x | [v1.0.8] bitz.customprofiles
x | [v1.0.1] bitz.darkmode_v4
x | [v1.0.4] bitz.moregames
x | [v1.0.2] blueblock6.cleanstartpos
x | [v1.0.3] capeling.coloured-wave-trail
x | [v1.1.4] capeling.icon_profile_2.2
x | [v4.1.10] cvolton.betterinfo
x | [v1.1.3] cvolton.misc_bugfixes
x | [v1.0.1] elnexreal.auto_priority
x | [v1.0.4] firee.GoldenBest
x | [v0.0.3] flafy.autonong
x | [v2.7.1] fleym.nongd
x | [v1.5.6] geode.custom-keybinds
x | [v2.0.0-beta.25] geode.loader
x | [v1.9.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.0.5] hjfod.gmd-api
x | [v1.0.1] hjfod.quick-volume-controls
x | [v1.1.0] itzkiba.id_hyperlinks
x | [v0.2.0] kevadroz.nocontrollerglyphs
x | [v1.2.0] khronophobia.shortcuts_menu
x | [v1.0.3] lynxdeer.autodeafen
x | [v1.3.2] m336.levelinfo
x | [v1.0.3] mat.run-info
x | [v1.1.0] polsk.level_quests
x | [v1.0.0] polsk.pause_settings
x | [v1.2.0] prevter.bettercrash
x | [v1.3.2] raydeeux.controlvanillasfx
x | [v1.3.3] raydeeux.fuckglow
  | [v1.0.2] relative.account_statuses
x | [v1.0.1] relative.advanced_song_search
x | [v1.0.3] relative.newgrounds_proxy
x | [v1.0.0] relative.scroll_faster_with_ctrl
x | [v1.0.0] riley.nogrounds
x | [v1.1.0] rynat.better_unlock_info
x | [v1.1.0] sofabeddd.colored_icon_kit
x | [v0.1.0] sse2.gj-music-manager
  | [v1.0.0] statuszer0.ultra_ldm
x | [v1.0.9] syzzi.click_between_frames
x | [v2024.229.0] tastyforreal.google-translate
x | [v1.1.0] techstudent10.button_sfx
x | [v2.11.0] techstudent10.discord_rich_presence
x | [v1.0.1] techstudent10.hide_locks
x | [v1.0.0-beta.8] thesillydoggo.comment_emojis
x | [v1.6.9] thesillydoggo.entersearch
x | [v1.0.3] thesillydoggo.icon_kit_switcher
x | [v1.2.0] thesillydoggo.moretags
x | [v1.6.8] tpdea.betterpause-Better
x | [v1.1.0] tpdea.sceneswitcher
x | [v1.1.0] tpdea.scroll_any_input
x | [v1.2.2] undefined0.autocheckpoint
x | [v1.1.0] uproxide.autosong
x | [v1.3.0] uproxide.more_difficulties
x | [v1.0.4] viper.newbestcomments
x | [v1.0.0] weebify.disable_black_glow
x | [v1.0.3] weebify.separate_dual_icons
x | [v1.0.0] xanii.auto_music_sync
x | [v1.0.1] xiyxs.recolored_music_library_songs
x | [v1.0.0] zilko.better_screenshots
x | [v1.0.1] zsa.percentage-bugfix

== Stack Allocations ==
- 0xEFECA4: 00EFECD3 (-> 0x1)
- 0xEFECA8: 00000000 (0i | 0u)
- 0xEFECAC: 1F0A47D8 (-> 0x72D050 -> 0x651742 -> GeometryDash.exe+0x3C1742 (<0x3c1710>+0x32))
- 0xEFECB0: 00000001 (1i | 1u)
- 0xEFECB4: 00EFED24 (-> 0xEFED4C -> 0xEFED8C -> 0x55C9E684 -> 0x55C9C751 -> geode.custom-keybinds.dll+0x1EC751 (keybinds::DeviceFilter::`default constructor closure'+0x1b75a1))
- 0xEFECB8: 55AFEDB4 (geode.custom-keybinds.dll+0x4EDB4 (keybinds::DeviceFilter::`default constructor closure'+0x19c04))
- 0xEFECBC: 20A7FFE0 (-> 0x55CA2A94 -> 0x55AFEC20 -> geode.custom-keybinds.dll+0x4EC20 (keybinds::DeviceFilter::`default constructor closure'+0x19a70))
- 0xEFECC0: 00EFED2C (-> 0x20A7FFE0 -> 0x55CA2A94 -> 0x55AFEC20 -> geode.custom-keybinds.dll+0x4EC20 (keybinds::DeviceFilter::`default constructor closure'+0x19a70))
- 0xEFECC4: 2C340D01 (-> 0x4040505 -> &"")
- 0xEFECC8: 55AFEC82 (geode.custom-keybinds.dll+0x4EC82 (keybinds::DeviceFilter::`default constructor closure'+0x19ad2))
- 0xEFECCC: 00EFECD3 (-> 0x1)
- 0xEFECD0: 01EFED8C (32501132i | 32501132u)
- 0xEFECD4: 00000000 (0i | 0u)
- 0xEFECD8: 55ADC111 (geode.custom-keybinds.dll+0x2C111 (keybinds::InvokeBindFilter::handle+0x1b1))
- 0xEFECDC: 00EFED8C (-> 0x55C9E684 -> 0x55C9C751 -> geode.custom-keybinds.dll+0x1EC751 (keybinds::DeviceFilter::`default constructor closure'+0x1b75a1))
- 0xEFECE0: 2C35A200 (&"C:\Windows\System32\msvcrt.dll")
- 0xEFECE4: 00000000 (0i | 0u)
- 0xEFECE8: 00000000 (0i | 0u)
- 0xEFECEC: 00000000 (0i | 0u)
- 0xEFECF0: 0000001C (28i | 28u)
- 0xEFECF4: 0000001F (31i | 31u)
- 0xEFECF8: 0000001F (31i | 31u)
- 0xEFECFC: 2D7F2DEC (-> 0x2D7F2DE0 -> 0x55C9ECE8 -> &"")
- 0xEFED00: 2C35A4A8 (&"robtop.geometry-dash/jump-p1")
- 0xEFED04: 0000001C (28i | 28u)
- 0xEFED08: 00EFECE0 (&"")
- 0xEFED0C: 00EFEDCC (-> 0xEFEDF4 -> 0xEFEEDC -> 0xEFEF70 -> 0xEFF280 -> 0xEFF428 -> 0xEFF4A4 -> 0xEFF55C -> 0xEFF808 -> 0xEFF864 -> 0xEFF8D0 -> 0xEFF8E8 -> 0xFFFFFFFF [...])
- 0xEFED10: 55AE4C50 (geode.custom-keybinds.dll+0x34C50 (keybinds::BindManager::save+0x940))
- 0xEFED14: 00000001 (1i | 1u)
- 0xEFED18: 2D7F2DEC (-> 0x2D7F2DE0 -> 0x55C9ECE8 -> &"")
- 0xEFED1C: 00EFED2C (-> 0x20A7FFE0 -> 0x55CA2A94 -> 0x55AFEC20 -> geode.custom-keybinds.dll+0x4EC20 (keybinds::DeviceFilter::`default constructor closure'+0x19a70))
- 0xEFED20: 00EFED8C (-> 0x55C9E684 -> 0x55C9C751 -> geode.custom-keybinds.dll+0x1EC751 (keybinds::DeviceFilter::`default constructor closure'+0x1b75a1))

**Comment by Cvolton** [comment] 2024-07-03 22:44
should either be fixed by now or caused by a different mod, please re-open with an updated crashlog if you still get the issue

**Closed by Cvolton** 2024-07-03 22:44 UTC
