### ISSUE TITLE
two keys pressed at once do not both register for same action

### ISSUE THREAD

**Issue by midiidev** [geode-sdk/CustomKeybinds#39] opened 2024-04-13 23:23 UTC
i'm trying to double click using H and J, but only one of the inputs is being sent through, while if i do W key + mouse, there's no issue

**Comment by Fleeym** [comment] 2024-04-18 20:11
This is intended behaviour for the "Jump" bind. Custom Keybinds does not edit how the mouse works, that's why it does work when combining keys and the mouse

**Comment by Fleeym** [comment] 2024-04-18 20:26
Scratch that, I just reread your question, I'll look into it 👍

**Comment by Fleeym** [comment] 2024-04-18 22:09
Fixed in the latest version (v1.5.3)

**Closed by Fleeym** 2024-04-18 22:09 UTC
